import { generateRandomName, randInt, clampStat, weightedPick, applyMoneyDelta } from "./character.js";

const SOCIAL_CIRCLE_MIN_AGE = 6;
const SOCIAL_CIRCLE_MIN_SIZE = 3;
const SOCIAL_CIRCLE_MAX_SIZE = 5;
let npcIdCounter = 0;

// One shared factory for a social-circle NPC, so classmates generated by
// the school system and the general social circle use the exact same
// shape (age, the same six-stat block the player has, friendship via
// `closeness`, and a separate `romance` meter) rather than two parallel
// NPC representations.
function createSocialNpc(namePools, countryId, age) {
  const gender = Math.random() < 0.5 ? "male" : "female";
  npcIdCounter += 1;
  return {
    id: `npc_${Date.now().toString(36)}_${npcIdCounter}`,
    name: generateRandomName(namePools, countryId, gender),
    type: "friend", // "friend" | "crush" | "romantic_interest"
    age,
    stats: {
      health: randInt(60, 100),
      happiness: randInt(50, 100),
      smarts: randInt(30, 70),
      looks: randInt(30, 70),
      fame: 0,
      reputation: randInt(30, 60),
    },
    closeness: randInt(40, 70),
    romance: 0,
  };
}

// Lazily generates a small, persistent group of classmate/friend NPCs the
// first time the character is old enough and something actually needs
// one -- not at birth, since a character who never triggers a social
// event shouldn't be carrying a pile of unused NPC records.
function ensureSocialCircle(character, namePools, countryId) {
  if (character.age < SOCIAL_CIRCLE_MIN_AGE) return;
  if (character.socialCircle && character.socialCircle.length > 0) return;

  const count = randInt(SOCIAL_CIRCLE_MIN_SIZE, SOCIAL_CIRCLE_MAX_SIZE);
  const circle = [];
  for (let i = 0; i < count; i++) {
    circle.push(createSocialNpc(namePools, countryId, character.age + randInt(-1, 1)));
  }
  character.socialCircle = circle;
}

// Every NPC the character actually knows by name: family (already
// generated at birth) plus the social circle above. Used to pick a
// specific, real subject for NPC-update flavor lines and dynamic events,
// instead of ever inventing a nameless "someone."
function getKnownNpcs(character) {
  const npcs = [];
  for (const parent of character.family?.parents ?? []) {
    // `relation` stays the base role ("mother"/"father") so templates can
    // still match on it regardless of relationship type; `relationLabel`
    // is what actually gets displayed, matching the birth narrative's
    // existing "step" prefixing.
    const relationLabel = parent.relationshipType === "step" ? `step${parent.role}` : parent.role;
    npcs.push({ name: parent.name, relation: parent.role, relationLabel });
  }
  for (const sibling of character.family?.siblings ?? []) {
    npcs.push({ name: sibling.name, relation: "sibling", relationLabel: "sibling" });
  }
  for (const npc of character.socialCircle ?? []) {
    npcs.push({ name: npc.name, relation: npc.type, relationLabel: npc.type });
  }
  return npcs;
}

// Promotes a random existing friend to a crush, returning the NPC record
// (or null if the character has no friends to develop feelings for yet).
function developCrush(character) {
  const friends = (character.socialCircle ?? []).filter((npc) => npc.type === "friend");
  if (friends.length === 0) return null;
  const target = friends[randInt(0, friends.length - 1)];
  target.type = "crush";
  return target;
}

// ---------- Shared NPC interactions ----------
// One canonical implementation of each interaction, reused everywhere an
// NPC can be interacted with (Friends list, Family, classmates, teacher)
// instead of every screen reimplementing its own version. Each mutates
// `character`/`npc` directly and returns the result line, so callers can
// either just show a toast or feed it into a modal.

function talk(character, npc) {
  npc.closeness = clampStat(npc.closeness + randInt(1, 4));
  character.stats.happiness = clampStat(character.stats.happiness + 1);
  const line = `You talked with ${npc.name} for a while.`;
  character.history.push(line);
  return line;
}

function hangOut(character, npc) {
  npc.closeness = clampStat(npc.closeness + randInt(3, 8));
  character.stats.happiness = clampStat(character.stats.happiness + 2);
  const line = `You hung out with ${npc.name}.`;
  character.history.push(line);
  return line;
}

const GIFT_COST = 20;

function giveGift(character, npc) {
  const paid = applyMoneyDelta(character, -GIFT_COST);
  if (!paid) {
    const line = `You wanted to get ${npc.name} a gift, but you don't have enough money right now.`;
    character.history.push(line);
    return line;
  }
  npc.closeness = clampStat(npc.closeness + randInt(8, 15));
  character.stats.happiness = clampStat(character.stats.happiness + 3);
  const line = `You gave ${npc.name} a small gift. They seemed to really appreciate it.`;
  character.history.push(line);
  return line;
}

// Nudges a friend toward a crush -- distinct from developCrush() above,
// which picks a *random* friend for a scripted event; this targets the
// specific NPC the player selected from a profile.
function developRomance(character, npc) {
  npc.type = "crush";
  npc.romance = clampStat((npc.romance ?? 0) + 15);
  character.stats.happiness = clampStat(character.stats.happiness + 5);
  const line = `You started developing feelings for ${npc.name}.`;
  character.history.push(line);
  return line;
}

// Shared ask-out success roll: higher closeness and already being a
// crush both raise the odds, but it's never guaranteed either way. Used
// anywhere a character asks an NPC out, whatever the occasion.
function rollAskOutSuccess(npc) {
  const closenessBonus = Math.floor((npc.closeness - 50) / 4);
  return randInt(0, 99) < (npc.type === "crush" ? 65 : 45) + closenessBonus;
}

function askOut(character, npc) {
  const succeeded = rollAskOutSuccess(npc);

  if (succeeded) {
    npc.type = "romantic_interest";
    npc.romance = clampStat((npc.romance ?? 0) + 20);
    npc.closeness = clampStat(npc.closeness + 10);
    character.stats.happiness = clampStat(character.stats.happiness + 8);
    const line = `You asked ${npc.name} out, and they said yes!`;
    character.history.push(line);
    return { succeeded: true, resultText: line };
  }

  npc.closeness = clampStat(npc.closeness - 5);
  character.stats.happiness = clampStat(character.stats.happiness - 3);
  const line = `You asked ${npc.name} out, but they turned you down.`;
  character.history.push(line);
  return { succeeded: false, resultText: line };
}

function askForHelp(character, teacher) {
  const closenessBonus = Math.floor((teacher.closeness - 50) / 5);
  const succeeded = randInt(0, 99) < 55 + closenessBonus;
  if (succeeded) {
    character.stats.smarts = clampStat(character.stats.smarts + randInt(2, 4));
    teacher.closeness = clampStat(teacher.closeness + 3);
    const line = `${teacher.name} took some extra time to help you understand the material.`;
    character.history.push(line);
    return line;
  }
  const line = `${teacher.name} was too busy to help today, but suggested you try again another time.`;
  character.history.push(line);
  return line;
}

function thankTeacher(character, teacher) {
  teacher.closeness = clampStat(teacher.closeness + randInt(3, 7));
  character.stats.happiness = clampStat(character.stats.happiness + 1);
  const line = `You thanked ${teacher.name} for their help this year.`;
  character.history.push(line);
  return line;
}

// ---------- Dynamic choice generators ----------
// A choice with `dynamic: "<id>"` resolves through one of these instead of
// static effects/outcomes, because the right options (which NPCs exist,
// who's eligible) can only be known at the moment the player picks it --
// not authored in advance in JSON. Each generator returns either:
//   { type: "resolve", effects?, resultText, flags?, skills?, hobbies? }
//     -- resolves immediately, same shape as a normal choice/outcome
//   { type: "followUp", event }
//     -- opens another event (with its own choices) right away
// New events needing this kind of runtime-dependent behavior register
// their own generator here rather than special-casing the engine.

const DYNAMIC_GENERATORS = {
  develop_crush_pursue(character, ctx) {
    ensureSocialCircle(character, ctx.namePools, ctx.countryId);
    const target = developCrush(character);
    if (!target) {
      return { type: "resolve", effects: { happiness: 1 }, resultText: "You don't really have anyone specific in mind right now." };
    }
    target.closeness = clampStat(target.closeness + 10);
    return {
      type: "resolve",
      effects: { happiness: 8, looks: 1 },
      resultText: `You started spending more time with ${target.name}, and it grew into a real crush. Things between you have been great.`,
    };
  },

  develop_crush_quiet(character, ctx) {
    ensureSocialCircle(character, ctx.namePools, ctx.countryId);
    const target = developCrush(character);
    if (!target) {
      return { type: "resolve", effects: { happiness: -1 }, resultText: "You don't really have anyone specific in mind right now." };
    }
    return {
      type: "resolve",
      effects: { happiness: -2 },
      resultText: `You've developed a crush on ${target.name}, but you're keeping it to yourself for now.`,
    };
  },

  ask_to_dance(character, ctx) {
    ensureSocialCircle(character, ctx.namePools, ctx.countryId);
    const prospects = (character.socialCircle ?? []).filter((npc) => npc.type === "friend" || npc.type === "crush");
    if (prospects.length === 0) {
      return { type: "resolve", effects: { happiness: -1 }, resultText: "You couldn't think of anyone in particular to ask, so you let the moment pass." };
    }
    return {
      type: "followUp",
      event: {
        id: "dance_ask_choice",
        trigger: "age_up",
        conditions: { minAge: 0, maxAge: 200 },
        text: "Who do you want to ask to the dance?",
        choices: prospects.map((npc) => ({
          label: npc.type === "crush" ? `${npc.name} (your crush)` : npc.name,
          dynamic: "resolve_dance_ask",
          dynamicArgs: { npcId: npc.id },
        })),
      },
    };
  },

  resolve_dance_ask(character, ctx) {
    const npc = (character.socialCircle ?? []).find((n) => n.id === ctx.dynamicArgs?.npcId);
    if (!npc) {
      return { type: "resolve", effects: {}, resultText: "You looked for them, but couldn't find them in time." };
    }
    const isCrush = npc.type === "crush";
    const succeeded = rollAskOutSuccess(npc);

    if (succeeded) {
      npc.closeness = clampStat(npc.closeness + 15);
      if (isCrush) npc.type = "romantic_interest";
      return {
        type: "resolve",
        effects: { happiness: 8, looks: 1 },
        resultText: `You finally asked ${npc.name} to the dance. They smiled and said yes.`,
      };
    }

    npc.closeness = clampStat(npc.closeness - 5);
    return {
      type: "resolve",
      effects: { happiness: -4 },
      resultText: `You asked ${npc.name} to the dance, but they turned you down. Awkward, but you'll survive.`,
    };
  },

  dance_with_friends(character, ctx) {
    ensureSocialCircle(character, ctx.namePools, ctx.countryId);
    const pool = character.socialCircle ?? [];
    const groupSize = Math.min(pool.length, randInt(2, 4));
    if (groupSize === 0) {
      return { type: "resolve", effects: { happiness: 2 }, resultText: "You ended up going alone and just people-watched most of the night." };
    }
    const shuffled = [...pool].sort(() => Math.random() - 0.5);
    const group = shuffled.slice(0, groupSize);
    const names = group.map((npc) => npc.name);
    const namesText = names.length === 1 ? names[0] : `${names.slice(0, -1).join(", ")} and ${names[names.length - 1]}`;

    // closenessDelta reflects how the night actually went for the group --
    // a fight shouldn't quietly strengthen the friendship just because a
    // group event happened.
    const outcomes = [
      { weight: 8, effects: { happiness: 6 }, closenessDelta: 8, text: `You went to the dance with ${namesText}. You spent most of the night laughing and taking terrible photos.` },
      { weight: 4, effects: { happiness: -2 }, closenessDelta: 0, text: `You went with ${namesText}, but the night felt a little flat and you left early.` },
      { weight: 3, effects: { happiness: -3 }, closenessDelta: -8, text: `You went with ${namesText}, but a stupid argument over nothing put a damper on the whole night.` },
      { weight: 3, effects: { happiness: 4, reputation: 1 }, closenessDelta: 12, text: `You went with ${namesText}, and the group ended up being the center of attention on the dance floor all night.` },
    ];
    const picked = weightedPick(outcomes);

    for (const npc of group) npc.closeness = clampStat(npc.closeness + picked.closenessDelta);

    return { type: "resolve", effects: picked.effects, resultText: picked.text };
  },

  skip_dance_alternative(character) {
    if (character.hobbies.includes("photography")) {
      return { type: "resolve", effects: { happiness: 2 }, skills: {}, resultText: "You skipped the dance and spent the evening working on your photography instead." };
    }
    if ((character.skills.programming ?? 0) >= 15) {
      return { type: "resolve", effects: { happiness: 2 }, skills: { programming: 2 }, resultText: "You skipped the dance and spent the night tinkering with code instead." };
    }
    if (character.stats.smarts >= 60) {
      return { type: "resolve", effects: { happiness: 1, smarts: 1 }, resultText: "You skipped the dance and got ahead on some reading instead." };
    }
    return { type: "resolve", effects: { happiness: 2 }, resultText: "You skipped the dance and watched movies with your family instead." };
  },
};

function resolveDynamicChoice(character, dynamicId, ctx) {
  const generator = DYNAMIC_GENERATORS[dynamicId];
  if (!generator) {
    return { type: "resolve", effects: {}, resultText: "" };
  }
  return generator(character, ctx);
}

// Lets other modules (school.js, and anything added later) contribute
// their own `dynamic` choice generators without app.js/events.js needing
// to know those modules exist, and without a circular import back into
// this file.
function registerDynamicGenerators(extra) {
  Object.assign(DYNAMIC_GENERATORS, extra);
}

export {
  ensureSocialCircle,
  getKnownNpcs,
  developCrush,
  resolveDynamicChoice,
  registerDynamicGenerators,
  createSocialNpc,
  talk,
  hangOut,
  giveGift,
  developRomance,
  askOut,
  askForHelp,
  thankTeacher,
  GIFT_COST,
};
